config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
validates :title, presence: true, length: {minimum: 3, maximum: 50}
validates :description, presence: true, length: {minimum: 3, maximum: 300}


end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, presence: true, 
	uniqueness: { case_sensitive: false }, 
	length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
	uniqueness: { case_sensitive: false },
	format: { with: VALID_EMAIL_REGEX }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
@articles = Article.all
	end

	def new
		@article = Article.new

	end

	def create
		@article = Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was successfully created."
redirect_to article_path(@article)

else render 'new'
	end
	end

	def show
		

	end

	def destroy
	

		@article.destroy
		flash[:notice] = "Article was successfully deleted"
		redirect_to articles_path

	end

	def edit
		

	end

	def update
	
		if @article.update(article_params)
			flash[:notice] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end

	end

	private

	def set_article
@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)

	end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The following errors prevented the articles from being created: </h2>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li>
        <%= msg %>
    </li>
    <% end %>
</ul>
<% end %>
<h1>
    <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit %>
    <% end %>
</h1>
<%= link_to 'Back to articles', articles_path %>

app/views/articles/edit.html.erb
<h1> Edit Article Page</h1>
<%= render 'form', article: @article %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1> This is the index page </h1>
<%= link_to 'Create new article', new_article_path %>
<br />
<br />
<% @articles.each do |article| %>
<tr>
    <td>
        <%= article.description %>
    </td>
    <td>
        <%= link_to 'Edit', edit_article_path(article) %>
    </td>
    <td>
        <%= link_to 'Show', article_path(article) %>
    </td>
    <td>
        <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>
    </td>
    <br />
    <% end %>

app/views/articles/new.html.erb
<h1> Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1> This is the articles show page</h1>
<p>
    <%= @article.title %>
</p>
<p>
    <%= @article.description %>
</p>
<%= link_to 'Edit article', edit_article_path(@article) %>
<%= link_to 'Back to articles', articles_path %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright <a href="#">Thehehehehe</a>
            by <a href="#">Wilson Horrell</a>
        </small>
        <nav>
            <ul>
                <li>
                    <%= link_to "About", about_path%>
                </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<ul>
    <li>
        <%= msg %>
    </li>
</ul>
<% end %>
<%= yield %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Articles', articles_path, class: 'nav-link' %>
            </li>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'New Article', new_article_path, class: 'nav-link' %>
                <li class="nav-item">
                    <%= link_to 'Sign out', '#', method: :delete, class: 'nav-link' %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign in', '#', class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign up', '#', class: 'nav-link' %>
                </li>
            </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <title>Homework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
    <div class="footer">
        <%= render 'layouts/footer' %>
    </div>
</body>

</html>

app/views/pages/about.html.erb
<h1> This is the about page</h1>
<%= link_to 'Back to home', root_path %>

app/views/pages/index.html.erb
<h1> This is the index page</h1>
<div class="col-10 offset-1">
    <div class=" center jumbotron">
        <h1> ALPHA BLOG </h1>
        <%= link_to "Sign up now", "#", class: "btn btn-primary btn-lg btn-xlarge" %>
    </div>
</div>